### ISSUE TITLE
Pin flipswitch to the right

### ISSUE THREAD

**Issue by Fisico** [diyhue/diyHueUI#12]
Pin the flipswitch to the right in the device view
![image](https://github.com/diyhue/diyHueUI/assets/329471/2d7fdc25-8acf-4d30-ac50-bad77a182355)

**Comment by hendriksen-mark** [comment]
https://github.com/diyhue/diyHueUI/blob/0119be7b16f06d764f16cb3deea0b637e055bbe1/src/components/FlipSwitch/flipswitch.scss#L17
