### ISSUE TITLE
Span select to the right

### ISSUE THREAD

**Issue by Fisico** [diyhue/diyHueUI#14]
Span the select to the right to align with the button.
![image](https://github.com/diyhue/diyHueUI/assets/329471/c8e14db1-bf5b-4d98-be48-5288d22171e6)

**Comment by hendriksen-mark** [comment]
https://github.com/diyhue/diyHueUI/blob/0119be7b16f06d764f16cb3deea0b637e055bbe1/src/components/SelectMenu/selectMenu.scss#L2
