### ISSUE TITLE
Glasseffect for menu on iOS not working

### ISSUE THREAD

**Issue by Fisico** [diyhue/diyHueUI#16]
The blur effect for the menu on is not working on iOS.

**Comment by hendriksen-mark** [comment]
This also happens on desktop.
If you go directliy to /#lights the menu item is also not selected

**Comment by Fisico** [comment]
fixed with [fc400eb](https://github.com/diyhue/diyHueUI/commit/fc400eb544c24a760b73b90a4af8bd6baf28c02e)
